Bootcamp/Bootcamp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

Bootcamp/library/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *


app_name = "library"
author_router = routers.SimpleRouter()
author_router.register(r'author', AuthorViewSet)
book_router = routers.SimpleRouter()
book_router.register(r'book', BookViewSet)

urlpatterns = [
    path('', LibraryHomePageView.as_view(), name='library_home_page'),
    path('authors/', AuthorListView.as_view(), name='authors_list'),
    path('authors/create/', AuthorCreateView.as_view(), name='authors_create'),
    path('authors/<int:pk>/', AuthorDetailsView.as_view(), name='authors_details'),
    path('authors/<int:pk>/update/', AuthorUpdateView.as_view(), name='authors_update'),
    path('authors/<int:pk>/delete/', AuthorDeleteView.as_view(), name='authors_delete'),
    path('books/', BookListView.as_view(), name='books_list'),
    path('books/create/', BookCreateView.as_view(), name='books_create'),
    path('books/<int:pk>/', BookDetailsView.as_view(), name='books_details'),
    path('books/<int:pk>/update/', BookUpdateView.as_view(), name='books_update'),
    path('books/<int:pk>/delete/', BookDeleteView.as_view(), name='books_delete'),
    path('api/v1/', include(author_router.urls)),
    path('api/v1/', include(book_router.urls)),
]

Bootcamp/library/models.py
from django.db import models
# from .validators import validate_spaces


class Book(models.Model):
    title = models.TextField(unique=True, null=False, blank=False)

    def __str__(self):
        return f'#{self.pk} {self.title}'


class Author(models.Model):
    name = models.TextField(unique=True, null=False, blank=False)
    books = models.ManyToManyField(Book, related_name='authors')

Bootcamp/library/forms.py
from django import forms
from .models import Author, Book


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': 'Введите ФИО автора',
            'books': 'Выберите книгу(-и) автора из списка',
        }


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Введите название книги',
        }

Bootcamp/library/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from rest_framework import viewsets
from .forms import AuthorForm, BookForm
from .models import Author, Book
from .serializers import AuthorSerializer, BookSerializer


class LibraryHomePageView(TemplateView):
    template_name = 'library/library-home-page.html'


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('library:authors_list')


class AuthorListView(ListView):
    queryset = Author.objects.all()


class AuthorDetailsView(DetailView):
    queryset = Author.objects.all()


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('library:authors_details', kwargs={'pk': self.object.pk})


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('library:authors_list')


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('library:books_list')


class BookListView(ListView):
    queryset = Book.objects.all()


class BookDetailsView(DetailView):
    queryset = Book.objects.all()


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('library:books_details', kwargs={'pk': self.object.pk})


class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('library:books_list')


class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

Bootcamp/library/templates/library/author_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить автора
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">
        Вы уверены, что хотите удалить <code>{{ object.name }}</code> из списка авторов?
    </h1>
    <div  class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-2" role="group" aria-label="First group">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-danger btn-lg">Подтвердить удаление</button>
            </form>
        </div>
        <div class="btn-group me-2" role="group" aria-label="Second group">
            <a href="{% url 'library:authors_details' pk=object.pk %}" class="btn btn-secondary btn-lg">
                Вернуться к информации об авторе
            </a>
        </div>
    </div>
{% endblock %}

Bootcamp/library/templates/library/author_detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.name}}
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">{{ object.name }}</h1>
    <ul class="list-group list-group-flush" style="margin-bottom: 70px;">
        <li class="list-group-item list-group-item-action disabled" aria-disabled="true">
            Список книг автора "{{object.name}}":
        </li>
        {% for object in object.books.all %}
            <li class="list-group-item list-group-item-action">
                <a href="{% url 'library:books_details' pk=object.pk %}" style="text-decoration: none;">
                    {{ object.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'library:authors_update' pk=object.pk %}" class="btn btn-primary btn-lg">
        Обновить информацию автора
    </a>
    <a href="{% url 'library:authors_delete' pk=object.pk %}" class="btn btn-danger btn-lg">
        Удалить автора
    </a>
    <a href="{% url 'library:authors_list' %}" class="btn btn-secondary btn-lg">
        Вернуться к списку авторов
    </a>
{% endblock %}

Bootcamp/library/templates/library/author_form.html
{% extends 'base.html' %}

{% block title %}
Создать нового автора
{% endblock %}

{% block content %}
<h1 class="display-1" style="margin-bottom: 100px; text-align: center;">Создать нового автора</h1>
<form method="post">
  {% csrf_token %}
  <div style="margin-bottom: 70px;">
    {% for field in form %}
      {{field.label_tag}}
      <div>
        {{field}}
      </div>
      {% if field.errors %}
        {% for error in field.errors %}
          {{error}}
        {% endfor %}
      {% endif %}
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary btn-lg">Создать нового автора</button>
  <a href="{% url 'library:authors_list' %}" class="btn btn-secondary btn-lg">
    Вернуться к списку авторов
  </a>
</form>
{% endblock %}

Bootcamp/library/templates/library/author_list.html
{% extends 'base.html' %}

{% block title %}
    Авторы
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">Авторы</h1>
        {% if object_list %}
            <table class="table table-hover" style="margin-bottom: 70px;">
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <th scope="row" style="width: 100px;">
                            #{{ object.pk }}
                        </th>
                        <td>
                            <a href="{% url 'library:authors_details' pk=object.pk %}" style="text-decoration: none;">
                                {{ object.name }}
                            </a>
                        </td>
                    <tr>
                {% endfor %}
              </tbody>
            </table>
        {% else %}
            <h3 class="display-3" style="margin-bottom: 70px; text-align: center;">
                Здесь пока что нет ни одной записи
            </h3>
        {% endif %}
    <div style="margin-bottom: 70px;">
        <a href="{% url 'library:authors_create' %}" class="btn btn-primary btn-lg">Создать нового автора</a>
        <a href="{% url 'library:library_home_page' %}" class="btn btn-secondary btn-lg">Вернуться на главную</a>
    </div>
{% endblock %}

Bootcamp/library/templates/library/author_update_form.html
{% extends 'base.html' %}

{% block title %}
Обновить информацию автора
{% endblock %}

{% block content %}
<h1 class="display-1" style="margin-bottom: 50px; text-align: center;">
  Обновить информацию автора {{ object.name }}
</h1>
<form method="post">
  {% csrf_token %}
  <div style="margin-bottom: 30px;">
    {% for field in form %}
      {{field.label_tag}}
      <div>
        {{field}}
      </div>
      {% if field.errors %}
        {% for error in field.errors %}
          {{error}}
        {% endfor %}
      {% endif %}
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary btn-lg">Обновить информацию автора</button>
  <a href="{% url 'library:authors_list' %}" class="btn btn-secondary btn-lg">
    Вернуться к списку авторов
  </a>
</form>
{% endblock %}

Bootcamp/library/templates/library/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Удалить книгу
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">
        Вы уверены, что хотите удалить <code>{{ object.title }}</code> из списка книг?
    </h1>
    <div  class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-2" role="group" aria-label="First group">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-danger btn-lg">Подтвердить удаление</button>
            </form>
        </div>
        <div class="btn-group me-2" role="group" aria-label="Second group">
            <a href="{% url 'library:books_details' pk=object.pk %}" class="btn btn-secondary btn-lg">
                Вернуться к информации о книге
            </a>
        </div>
    </div>
{% endblock %}

Bootcamp/library/templates/library/book_detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.title}}
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">{{ object.title }}</h1>
    <ul class="list-group list-group-flush" style="margin-bottom: 70px;">
        <li class="list-group-item list-group-item-action disabled" aria-disabled="true">
            Список авторов книги "{{object.title}}":
        </li>
        {% for object in object.authors.all %}
            <li class="list-group-item list-group-item-action">
                <a href="{% url 'library:authors_details' pk=object.pk %}" style="text-decoration: none;">
                    {{ object.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'library:books_update' pk=object.pk %}" class="btn btn-primary btn-lg">
        Обновить информацию книги
    </a>
    <a href="{% url 'library:books_delete' pk=object.pk %}" class="btn btn-danger btn-lg">
        Удалить книгу
    </a>
    <a href="{% url 'library:books_list' %}" class="btn btn-secondary btn-lg">
        Вернуться к списку книг
    </a>
{% endblock %}

Bootcamp/library/templates/library/book_form.html
{% extends 'base.html' %}

{% block title %}
    Создать новую книгу
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">Создать новую книгу</h1>
    <form method="post">
        {% csrf_token %}
        <div style="margin-bottom: 70px;">
            {{ form }}
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Создать новую книгу</button>
        <a href="{% url 'library:books_list' %}" class="btn btn-secondary btn-lg">
            Вернуться к списку книг
        </a>
    </form>
{% endblock %}

Bootcamp/library/templates/library/book_list.html
{% extends 'base.html' %}

{% block title %}
    Книги
{% endblock %}

{% block content %}
    <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">Книги</h1>
        {% if object_list %}
            <table class="table table-hover" style="margin-bottom: 70px;">
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <th scope="row" style="width: 100px;">
                            #{{ object.pk }}
                        </th>
                        <td>
                            <a href="{% url 'library:books_details' pk=object.pk %}" style="text-decoration: none;">
                                {{ object.title }}
                            </a>
                        </td>
                    <tr>
                {% endfor %}
              </tbody>
            </table>
        {% else %}
            <h3 class="display-3" style="margin-bottom: 70px; text-align: center;">
                Здесь пока что нет ни одной записи
            </h3>
        {% endif %}
    <div style="margin-bottom: 70px;">
        <a href="{% url 'library:books_create' %}" class="btn btn-primary btn-lg">Создать новую книгу</a>
        <a href="{% url 'library:library_home_page' %}" class="btn btn-secondary btn-lg">Вернуться на главную</a>
    </div>
{% endblock %}

Bootcamp/library/templates/library/book_update_form.html
{% extends 'base.html' %}

{% block title %}
  Обновить информацию книги
{% endblock %}

{% block content %}
  <h1 class="display-1" style="margin-bottom: 100px; text-align: center;">
    Обновить информацию книги {{ object.title }}
  </h1>
  <div>
    <form method="post">
      {% csrf_token %}
      <div style="margin-bottom: 70px;">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary btn-lg">Обновить информацию книги</button>
      <a href="{% url 'library:books_list' %}" class="btn btn-secondary btn-lg">
        Вернуться к списку книг
      </a>
    </form>
  </div>
{% endblock %}

Bootcamp/library/templates/library/library-home-page.html
{% extends 'base.html' %}

{% block title %}
Flibusta Home Page
{% endblock %}

{% block content %}
<h1 class="display-1" style="margin-bottom: 100px; text-align: center;">Flibusta</h1>
<div class="d-grid gap-2 col-6 mx-auto">
  <a href="{% url 'library:authors_list' %}" class="btn btn-primary"> Авторы </a>
  <a href="{% url 'library:books_list' %}" class="btn btn-primary"> Книги </a>
</div>
{% endblock %}

Bootcamp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'library/css/bootstrap.min.css' %}">
    <script src="{% static 'library/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="container my-md-4 bd-layout">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>